[package]
name = "finima-feed"
version.workspace = true
edition = "2021"

[dev-dependencies]
rust_decimal = { workspace = true }

[dependencies]
finima-core = { path = "../finima-core" }
finima-llm = { path = "../finima-llm", default-features = false }
feed-rs = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
