use axum::extract::{Path, Query, State};
use axum::Json;
use serde::{Deserialize, Serialize};

use finima_auth::middleware::AuthUser;
use finima_core::AppError;
use finima_feed::{FeedArticle, FeedFetcher, FeedSource, RawArticle, RelevanceScorer};

use crate::state::AppState;

// ---------------------------------------------------------------------------
// Request / response types
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
pub struct FeedQuery {
    #[serde(default = "default_page")]
    pub page: u32,
    #[serde(default = "default_per_page")]
    pub per_page: u32,
    pub topic: Option<String>,
}

fn default_page() -> u32 {
    1
}
fn default_per_page() -> u32 {
    20
}

#[derive(Debug, Serialize)]
pub struct FeedResponse {
    pub data: Vec<FeedArticle>,
    pub total: usize,
    pub page: u32,
    pub per_page: u32,
}

#[derive(Debug, Serialize)]
pub struct SummaryResponse {
    pub article_id: String,
    pub summary: String,
}

// ---------------------------------------------------------------------------
// GET /api/feed
// ---------------------------------------------------------------------------

pub async fn list_feed(
    _auth: AuthUser,
    State(state): State<AppState>,
    Query(params): Query<FeedQuery>,
) -> Result<Json<FeedResponse>, AppError> {
    let config = state.config();

    // Convert configured feed sources to the feed crate's type.
    let sources: Vec<FeedSource> = config
        .feed
        .sources
        .iter()
        .map(|s| FeedSource {
            name: s.name.clone(),
            url: s.url.clone(),
            topic: s.topic.clone(),
            enabled: true,
        })
        .collect();

    // Fetch articles from all sources.
    let fetcher = FeedFetcher::new();
    let results = fetcher.fetch_all(&sources).await;

    // Collect all successfully fetched articles.
    let mut all_articles: Vec<RawArticle> = Vec::new();
    for (_source, result) in results {
        if let Ok(articles) = result {
            all_articles.extend(articles);
        }
    }

    // Apply topic filter if specified.
    if let Some(ref topic) = params.topic {
        let lower_topic = topic.to_lowercase();
        all_articles.retain(|a| a.topics.iter().any(|t| t.to_lowercase() == lower_topic));
    }

    // Sort by published date (newest first).
    all_articles.sort_by(|a, b| b.published_at.cmp(&a.published_at));

    let total = all_articles.len();

    // Paginate.
    let start = ((params.page - 1) * params.per_page) as usize;
    let page_articles: Vec<_> = all_articles
        .into_iter()
        .skip(start)
        .take(params.per_page as usize)
        .collect();

    // Score and convert to response articles.
    // For now, use empty user context (would be populated from user's accounts).
    let feed_articles: Vec<FeedArticle> = page_articles
        .into_iter()
        .enumerate()
        .map(|(i, raw)| {
            let score = RelevanceScorer::score(&raw, &[], &[]);
            FeedArticle {
                id: format!("article-{}-{}", params.page, i),
                title: raw.title,
                url: raw.url,
                source: raw.source_name,
                date: raw.published_at.map(|d| d.to_rfc3339()),
                summary: None,
                relevance_score: score,
                topics: raw.topics,
            }
        })
        .collect();

    Ok(Json(FeedResponse {
        data: feed_articles,
        total,
        page: params.page,
        per_page: params.per_page,
    }))
}

// ---------------------------------------------------------------------------
// GET /api/feed/:id/summary
// ---------------------------------------------------------------------------

pub async fn get_article_summary(
    _auth: AuthUser,
    State(state): State<AppState>,
    Path(article_id): Path<String>,
) -> Result<Json<SummaryResponse>, AppError> {
    let llm_client = state.llm_client();
    let config = state.config();

    // Parse the article ID to extract page and index.
    // IDs follow the pattern "article-{page}-{index}" as generated by list_feed.
    let parts: Vec<&str> = article_id.split('-').collect();
    let (page, index) = match parts.as_slice() {
        ["article", page_str, index_str] => {
            let page: u32 = page_str
                .parse()
                .map_err(|_| AppError::BadRequest("Invalid article ID format".to_string()))?;
            let index: usize = index_str
                .parse()
                .map_err(|_| AppError::BadRequest("Invalid article ID format".to_string()))?;
            (page, index)
        }
        _ => {
            return Err(AppError::BadRequest(
                "Invalid article ID format".to_string(),
            ))
        }
    };

    // Re-fetch articles from all configured sources to find the requested one.
    let sources: Vec<FeedSource> = config
        .feed
        .sources
        .iter()
        .map(|s| FeedSource {
            name: s.name.clone(),
            url: s.url.clone(),
            topic: s.topic.clone(),
            enabled: true,
        })
        .collect();

    let fetcher = FeedFetcher::new();
    let results = fetcher.fetch_all(&sources).await;

    let mut all_articles: Vec<RawArticle> = Vec::new();
    for (_source, result) in results {
        if let Ok(articles) = result {
            all_articles.extend(articles);
        }
    }

    // Sort by published date (newest first) to match list_feed ordering.
    all_articles.sort_by(|a, b| b.published_at.cmp(&a.published_at));

    // Compute the same offset used in list_feed pagination.
    let per_page: u32 = 20; // default per_page from list_feed
    let start = ((page - 1) * per_page) as usize;
    let absolute_index = start + index;

    let article = all_articles.get(absolute_index).ok_or(AppError::NotFound)?;

    let summary = finima_feed::ArticleSummarizer::summarize(
        llm_client.as_ref(),
        &article.title,
        &article.content_snippet,
    )
    .await
    .map_err(|e| AppError::InternalError(e.to_string()))?;

    Ok(Json(SummaryResponse {
        article_id,
        summary,
    }))
}
